---
# tasks file for wordpress
- name: Install EPEL release for nginx
  yum: name=epel-release state=present

- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract Wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/usr/share/nginx/html

- name: Update Wordpress config file
  copy: src=files/wp-config-sample.php dest=/usr/share/nginx/html/wordpress/wp-config.php

- name: Set permission
  file:
   path: /usr/share/nginx/html/wordpress
   owner: nginx
   group: nginx
   mode: 0755
   recurse: yes
