---
# tasks file for Configure NTP
- name: Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version"
  copy: 
    src: files/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes 
- name: Enable the service NTP at boot
  shell: 'systemctl enable ntpd && systemctl start ntpd'
